### ISSUE TITLE
Links to LineageOS are broken for some devices

### ISSUE THREAD

**Issue by regagain** [Divested-Mobile/divestos-website#1]
Hi!

Thank you very much for this very exciting project.

The device info and install links on https://divestos.org/index.php?page=devices&base=LineageOS are broken for some devices, for example Fairphone 2, Yandex Phone, Pixel 3.

A very minor thing, obviously, but I thought I'd let you know.

**Comment by SkewedZeppelin** [comment]
Thanks.

Some devices simply don't have pages on the LineageOS wiki, such as the Pixel 2/3.

Other devices such as the Yandex Phone and Fairphone 2 have the wrong capitalization.
(amber vs Amber and fp2 vs FP2)
I will look to put a fix in for that.
