### ISSUE TITLE
Bromite Basic Fingerprinting Protection

### ISSUE THREAD

**Issue by uazo** [Divested-Mobile/DivestOS-Website#11]
Ciao Tad,
we don't know each other directly but, for better or worse, I am continuing carl's work on bromite.
I would kindly ask you, with reference to https://divestos.org/pages/browsers and with a view to improving the browser, on what basis do you define "Basic" the Fingerprinting protection in bromite? could you point out what you think is missing?
thank you in advance!

**Comment by SkewedZeppelin** [comment]
Brave and Firefox RFP cover many aspects, Bromite only has a dozen or so?

**Comment by SkewedZeppelin** [comment]
There is no study or in-depth technical analysis here or even definition of my categorization, the labels are just based off of my understanding.

I'm not saying I am right here, I'm asking you as the author of many of the patches for clarification.

**Comment by uazo** [comment]
thanks for the explanation.

> I'm not saying I am right here

OK, I understand.

> I'm asking you as the author of many of the patches for clarification.

perfect I thank you. no, honestly it is not my goal to list the differences with brave/firefox and bromite, I know brave's code but not firefox's, I know (more or less) what brave does but not what firefox does.
And then I would be biased, I would prefer an audit from someone outside the project.

maybe, if I may, but I don't feel obligated, it's just a suggestion from a technician to a technician, then you do what you want, I would add a post in which you indicate the lack of sources and that it's a personal opinion, unless it's already there and I haven't seen it (and then I apologize).
But that was not the goal of my question, which was just to have items to improve the browser.

thank you anyway!
