### ISSUE TITLE
Error Message: DivestOS F-Droid Repos

### ISSUE THREAD

**Issue by rmskhen** [Divested-Mobile/DivestOS-Website#13]
F-Droid on Android shows **an error message** concerning both official DivestOS repos: `"{DivestOS F-Droid repo link}: Chain validation failed → Chain validation failed. All other repos didn't create errors."`

The error message appears when:
- Checking for updates on the F-Droid Android app with any of the official DivestOS repos added.
- Adding any of the official DivestOS repos on the the F-Droid Android app.

**Comment by SkewedZeppelin** [comment]
what version of Android are you using?

**Comment by SkewedZeppelin** [comment]
that sounds mostly fine, can you just confirm it still happens after:
- a reboot
- disabling the blocker?
