### ISSUE TITLE
Information about Session messenger is outdated or wrong.

### ISSUE THREAD

**Issue by onlineapps-cloud** [Divested-Mobile/DivestOS-Website#23]
hi i saw on your page https://divestos.org/pages/messengers that Session messenger not support E2EE uses PFS, 
![image](https://github.com/Divested-Mobile/DivestOS-Website/assets/69077240/d8762d5e-c002-4ce7-ba7c-f04f3df6a99a)
on they site i found information that they ise E2EE uses PFS.
excerpt from the documentation at the link: https://arxiv.org/pdf/2002.04609.pdf
![image](https://github.com/Divested-Mobile/DivestOS-Website/assets/69077240/075a17d1-1965-414f-87a7-f67a56b9c682)
![image](https://github.com/Divested-Mobile/DivestOS-Website/assets/69077240/29a2d0be-4982-4975-ae4f-136f89b5ab3e)
![image](https://github.com/Divested-Mobile/DivestOS-Website/assets/69077240/7ce85cec-adc3-40a0-9e41-5eba4e8e49eb)
If Session use same protocol as Signal, and signal support PFS, then Session support to?! :) please correct table it it's outdated or wrong infromation. thanks, best regards.

**Comment by SkewedZeppelin** [comment]
Session does not support PFS.
Session protocol is based on Signal protocol which does support PFS, but Session doesn't.

https://getsession.org/session-protocol-explained
> First things first, let’s talk about what we’re leaving behind: Perfect Forward Secrecy (PFS) and deniability.

Dicussion here: https://github.com/orgs/privacyguides/discussions/296#discussioncomment-1756211
