### ISSUE TITLE
Issues on security bugfix count and typo in ch-dates.txt

### ISSUE THREAD

**Issue by phmlumin** [Divested-Mobile/DivestOS-Website#24]
Chromium version 118.0.5993.80 includes 1 security fix
https://chromereleases.googleblog.com/2023/10/chrome-for-android-update_17.html
https://chromereleases.googleblog.com/2023/10/stable-channel-update-for-desktop_17.html

Chromium version 111.0.5563.58 includes 41 security fixes instead of 40, and none of them are of critical severity
https://chromereleases.googleblog.com/2023/03/stable-channel-update-for-desktop.html

The date of version 94.0.4606.85 for /e/OS is mistyped as "20221/12/06"

**Comment by SkewedZeppelin** [comment]
111.0.5563.58 did have a critical https://bugs.chromium.org/p/chromium/issues/detail?id=1422099

I've made the other adjustments will push in a minute, thanks!
