### ISSUE TITLE
Threema is Open Source

### ISSUE THREAD

**Issue by fossdd** [Divested-Mobile/divestos-website#3]
In this line is set that Threema isn't Open Source. This is since 22. December the mobile Application of Threema is Open Source:

https://github.com/threema-ch/threema-android

The Server is still properitary and can't hosted self.

https://github.com/Divested-Mobile/divestos-website/blob/ac438f3e1499ec010504148707380a824ebcb130/pages/messengers.html#L254

**Comment by SkewedZeppelin** [comment]
@fossfd
Fixed, thanks!
