### ISSUE TITLE
Update website to account for 5G?

### ISSUE THREAD

**Issue by tcrxt** [Divested-Mobile/DivestOS-Website#30]
The [post-install](https://divestos.org/pages/post_install) currently reads:

https://github.com/Divested-Mobile/DivestOS-Website/blob/d713dc37fc824b2cddb3045c73f2f5c9a702541f/stubs/post_install.html#L15

Is this still accurate if 5G is available as well? If the network offers:

- LTE Only,
- 5G,
- LTE,
- 3G

for instance, which one should be preferred?

**Comment by SkewedZeppelin** [comment]
LTE Only still, anecdotally 5g has higher battery usage
