### ISSUE TITLE
[messengers] Conversations is in f-droid

### ISSUE THREAD

**Issue by foxjaw** [Divested-Mobile/DivestOS-Website#32]
https://divestos.org/pages/messengers

Conversations app (1st in the list) is already in f-droid  
https://f-droid.org/packages/eu.siacs.conversations/

Change `F-Droid: No` to `F-Droid: Yes`

**Comment by SkewedZeppelin** [comment]
I think you misread it:
> Non-Free Dependencies: F-Droid: No, Play: Yes

The line means the F-Droid variant is fully FOSS, but the Play Store variant contains proprietary dependencies.
