### ISSUE TITLE
Can not access the page of `divestos.org`

### ISSUE THREAD

**Issue by cyberboh** [Divested-Mobile/DivestOS-Website#34]
Is it down? Because i see on `https://www.isitdownrightnow.com/divestos.org.html` it's down
![image](https://github.com/Divested-Mobile/DivestOS-Website/assets/99109969/86f5d85b-7636-4446-8a97-7c94632cc96d)

**Comment by SkewedZeppelin** [comment]
Neither of the servers are down.
