### ISSUE TITLE
a-dates.txt: add LineageOS

### ISSUE THREAD

**Issue by dktzde** [Divested-Mobile/DivestOS-Website#35]
Is this page generated by a script?

if no: May I add LineagOS? (I have a Pixel 3 and save the update date anyway - knowing that it is only "nightly" and not RC)

if yes: I would like to see LineageOS and maybe [iodéOS](https://iode.tech/) added.

**Comment by SkewedZeppelin** [comment]
@dktzde 
The page is updated entirely by hand.
I would like to see them both, but:
- LineageOS ships the monthly ASB on different days of the week depending on the device.
- iodeOS doesn't publish public changelogs.

**Comment by dktzde** [comment]
> I would like to see them both,

I'm happy that you think so :-)
> but:
> * LineageOS ships the monthly ASB on different days of the week depending on the device.

I am aware of this - that's why I also wrote the cell phone I use.
I will add a footnote so that it is clear what the data refers to. I will prepare a corresponding change request, then you can see if that works for you. What do you think?
>   * Lineage has even entirely paused all builds because of the QPR2 changes: [LineageOS/hudson@f4adb0c](https://github.com/LineageOS/hudson/commit/f4adb0c30793cba4118a020c161bd435b4551669)

I started collecting data in January (2024-02-15; 2024-01-15) - March ASB will probably take a while longer.

**Comment by SkewedZeppelin** [comment]
@dktzde 
there is a complete index of all builds here thanks to @timschumi: https://lineage-archive.timschumi.net/MD5SUMS

you can probably compare the merge dates of each ASB and pick the earliest dated release after as the release date.

**Comment by timschumi** [comment]
> there is a complete index of all builds here thanks to timschumi: [lineage-archive.timschumi.net/MD5SUMS](https://lineage-archive.timschumi.net/MD5SUMS)

Note that this list is _not_ complete, it at most covers everything starting from December 2022 (which is roughly when I started to check in build hashes into a database) and the random collections of builds that I was able to gather from other sources.

Not that you'd need information of historic builds for the list anyways, once the ASB changes have been merged, all builds that were started after that (on that particular branch) will have those patches. Therefore, you can just note down the merge date (or, if you want to be sure that you aren't mislabeling builds, the merge date + 1).

**Comment by SkewedZeppelin** [comment]
thanks @timschumi 

most of the LineageOS ASB patchsets are already linked from https://divestos.org/pages/patch_counts
I can go through them sometime, unless you really want to do them @dktzde

**Comment by dktzde** [comment]
Thank you very much. It seems to me that https://divestos.org/pages/patch_counts is a good source. So there is also not the delay of up to 7 days - depending on the model. I also noticed that it is necessary to differ by branches. I will try to add [LOS 20](https://review.lineageos.org/q/topic:T_asb_2024-02) and [LOS 21](https://review.lineageos.org/q/topic:U_asb_2024-02).

**Comment by SkewedZeppelin** [comment]
![Screenshot from 2024-03-27 16-41-57](https://github.com/Divested-Mobile/DivestOS-Website/assets/8296104/b3acb53b-369a-426e-8e51-7e5a441cb018)

OK
@dktzde added 20 in https://github.com/Divested-Mobile/DivestOS-Website/pull/36/
and I added 17/18/19 in 6ad38e2b6c20877bfd60ecf353896ac00b5b3a5b

will need to do something about the width, maybe make it into an actual html table again

I'd also still like to add iode, @vincentvidal do you have historical dates of when you did ASB releases?
ref: https://divestos.org/misc/a-dates.txt

**Comment by dktzde** [comment]
> will need to do something about the width, maybe make it into an actual html table again

Could you maybe consider splitting it into two tables?
One with the older Android versions and one with the "current" ones.

e.g.:
a-dates.txt:
Android DivestOS 14.1 DivestOS 15.1 DivestOS 16.0 DivestOS 17.1 LineageOS 17.1 DivestOS 18.1 LineageOS 18.1

a2-dates.txt
Android GrapheneOS DivestOS 19.1 LineageOS 19 DivestOS 20.0 LineageOS 20 CalyxOS /e/OS iode

**Comment by dktzde** [comment]
> I'd also still like to add iode, [...]

I have just found out that the iode news app (com.iode.news), which is distributed via the [iode F-Droid Repro](https://raw.githubusercontent.com/iodeOS/fdroid/master/fdroid/repo?fingerprint=EC43610D9ACCA5D2426EB2D5EB74331930014DE79D3C3ACBC17DFE58AA12605F), contains the relevant data for the last 2 years. May I add these? Between which columns do you want to insert iode OS? (ASB always seems to appear towards the end of the month, sometimes a little later).

**Comment by SkewedZeppelin** [comment]
@dktzde I've added them, would you mind double checking it?

**Comment by SkewedZeppelin** [comment]
wip: https://divestos.org/pages/patch_history.html

**Comment by SkewedZeppelin** [comment]
finished: https://divestos.org/pages/patch_history.html

thanks again @dktzde

**Comment by dktzde** [comment]
> edit: is it this? https://gitlab.com/iode/static/-/blob/main/posts.json?ref_type=heads

Yes, it is.

> seems so, I'm adding it.

Thanks for adding it.

> @dktzde I've added them, would you mind double checking it? thanks

Of course. - Already did.

> finished: https://divestos.org/pages/patch_history

Thank you a lot too!
