### ISSUE TITLE
build guide: Unclear instructions on vendor blobs

### ISSUE THREAD

**Issue by ryneeverett** [Divested-Mobile/DivestOS-Website#40]
It reads on /stubs/build.html:

```sh
#Add the vendor blobs!
##You must find these repos yourself. Extracting them is NOT correct.
```

I'm not sure what these "repos" are. If the blobs aren't extracted from the device then where do they come from?

**Comment by SkewedZeppelin** [comment]
The exact section you need is already there https://github.com/Divested-Mobile/DivestOS-Build/blob/master/Manifests/Manifest_LAOS-20.0.xml#L335-L431

You must color in the lines.
