### ISSUE TITLE
XMPP Community inaccessible

### ISSUE THREAD

**Issue by ManDay** [Divested-Mobile/DivestOS-Website#42]
The official DivestOS XMPP rooms have been in moderated mode for weeks if not months, all means of PM or contacting the moderators are disabled, there is no hint in the topic as to how to get voice and even attempts by intermediaries to ask for voice on someone's behalf have been ignored.

All in all one gets a pretty distinct "GTFO" vibe from this.

**Comment by SkewedZeppelin** [comment]
You've been marked a member.
