### ISSUE TITLE
Unclear markup (cross out, asterisk) in FAQ

### ISSUE THREAD

**Issue by engelhro** [Divested-Mobile/DivestOS-Website#9]
Hello,

I have two questions regarding the markup used in the [FAQ](https://divestos.org/index.php?page=faq):

1. Why are some models **struck through** in the [recommendation section](https://divestos.org/index.php?page=faq#recommendPhone)? I own such a device (OnePlus 7 Pro = guacamole) and I'm looking into DivestOS.
    - Aren't those models recommended all? If so, why?
    - Or where they once recommended and are not any longer? And if so, again: what are the reasons for the removed recommendation?

2. Similar: what does the **asterisk**(*) mean that is attached to some models (this applies also to section [CFI kernels](https://divestos.org/index.php?page=faq#kernelCFI), whatever "CFI" means)?

There most probably exist some restrictions or specific things to be considered, but that star as footnote resp. reference is not resolved…

It would be great to have an *explanation or a legend for the various markup used*, as mentioned especially for the asterisk and crossed out parts.

Thanks for such improvement and better understandability!

Oh, and I just saw: also on the [download page](https://divestos.org/index.php?page=devices&base=LineageOS&golden=false) the asterisk is used (for the "Relockable" information) without its meaning being given.

**Comment by SkewedZeppelin** [comment]
I'll try to go through the website sometime and make these clearer.

> Why are some models struck through in the [recommendation section](https://divestos.org/index.php?page=faq#recommendPhone)?

OnePlus 7 series was recommended, but OnePlus removed the ability to relock the system in a firmware update sadly.

> Similar: what does the asterisk [...] (this applies also to section [CFI kernels](https://divestos.org/index.php?page=faq#kernelCFI), whatever "CFI" means)?

That is a wildcard there, not an asterisk. Meant to include hotdogb and guacamoleb.

> also on the [download page](https://divestos.org/index.php?page=devices&base=LineageOS&golden=false) the asterisk is used (for the "Relockable" information)

That is an asterisk, meant to be that it may actually be possible or at least in some circumstances, but highly unlikely.
